spring:
  security:
    oauth2:
      client:
        kakao:
          authorization-grant-type: authorization_code
          client-id: 0647469b8a94c9ade88ef28aafddec73
          client-secret: wNQ9hbVlRNqj24VgWOiKPziZc0VDwbZW
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          scope:
            - profile_nickname
            - account_email
          client-name: Kakao
          client-authentication-method: POST
        provider:
          kakao:
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id